import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "welocme": "welcome to Nurse App",
          "guide": "your perfect guide",
          "continu": "continue",
          "takemedicin": "take medecin",
          "changeonwound": "change on wound",
          "catheterization": "catheterization",
          "injection": "injection",
          "pressure": "pressure gauge",
          "addpatient": "add patient",
          "id": "id",
          "name": "name",
          "caringtype": "caring type",
          "reminder": "reminder",
          "save": "save",
          "language": "change language",
          "delete": "delete",
          "confirm": "Are you sure you want to delete this patient?",
          "yes": "yes",
          "no": "no",
          "patients": "patients",
          'validate1': 'you must provide name',
          'validate2': 'you must provide room number',
          'start': 'Start Adding Patients !',
          'room': 'Room',
          'select': 'select a type',
        },
        'ar': {
          "welocme": "اهلا بك في تطبيق الممرض",
          "guide": "دليلك المثالي",
          "continu": "متابعة",
          "takemedicin": "اخذ دواء",
          "changeonwound": "تغيير على جرح",
          "catheterization": "قسطرة",
          "injection": "حقنة",
          "pressure": "قياس ضغط",
          "addpatient": "اضافة مريض",
          "id": "الرقم",
          "name": "الاسم",
          "caringtype": "نوع العناية",
          "reminder": "منبه",
          "save": "حفظ",
          "language": "تغيير اللغة",
          "delete": "حذف",
          "confirm": "هل انت متاكد من حذف المريض ؟",
          "yes": "نعم",
          "no": "لا",
          "patients": "المرضى",
          'validate1': 'يجب اضافة اسم',
          'validate2': 'يجب اضافة رقم غرفة',
          'start': 'ابدأ باضافة المرضى !',
          'room': 'غرفة',
          'select': 'اختر نوعا',
        },
        'fr': {
          "welocme": "bienvenue dans application infirmiere",
          "guide": "votre guide parfait",
          "continu": "continuer",
          "takemedicin": "prendre des medicaments",
          "changeonwound": "changement sur blessure",
          "catheterization": "catheterisme",
          "injection": "injection",
          "pressure": "manometre",
          "addpatient": "ajouter un patient",
          "id": "identifiant",
          "name": "nom",
          "caringtype": "genre attentionne",
          "reminder": "rappel",
          "save": "sauvegarder",
          "language": "changer de langue",
          "delete": "supprimer",
          "confirm": "etes-vous sur de vouloir supprimer ce patient ?",
          "yes": "oui",
          "no": "non",
          "patients": "les patients",
          'validate1': 'vous devez fournir le nom',
          'validate2': 'vous devez fournir le numéro de chambre',
          'start': 'Commencez à ajouter des patients !',
          'room': 'Chambre',
          'select': 'selectionnez un type',
        }
      };
}
